# Generated by Django 2.0.2 on 2018-12-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='duizhao',
            fields=[
                ('宠物编号', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('宠物名字', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='shujuku',
            fields=[
                ('账号编号', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('石头数量', models.CharField(blank=True, max_length=100)),
                ('等级', models.CharField(blank=True, max_length=100)),
                ('更新时间', models.CharField(blank=True, max_length=100)),
                ('宠物', models.TextField()),
            ],
        ),
    ]
