# Generated by Django 2.0 on 2019-03-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pad', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='duizhao',
        ),
    ]
