# Generated by Django 2.0 on 2019-03-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pad', '0002_delete_duizhao'),
    ]

    operations = [
        migrations.CreateModel(
            name='duizhao',
            fields=[
                ('宠物编号', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('宠物名字', models.CharField(blank=True, max_length=100)),
                ('宠物价值', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
