# Generated by Django 2.0.2 on 2019-04-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pad', '0003_duizhao'),
    ]

    operations = [
        migrations.CreateModel(
            name='huancun',
            fields=[
                ('唯一键', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('账号编号', models.CharField(max_length=100)),
                ('石头数量', models.CharField(blank=True, max_length=100)),
                ('等级', models.CharField(blank=True, max_length=100)),
                ('宠物', models.TextField()),
                ('是否上传', models.CharField(default='1', max_length=2)),
                ('更新时间', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
