# Generated by Django 2.0 on 2020-01-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pad', '0005_auto_20191221_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duizhao',
            name='更新时间',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField(),
        ),
    ]
