# Generated by Django 2.0 on 2020-01-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pad', '0006_auto_20200104_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hot',
            name='number',
        ),
        migrations.AlterField(
            model_name='hot',
            name='name',
            field=models.TextField(),
        ),
    ]
